import type { ItineraryDay } from "./schema";

/**
 * Starter content for Explore Bound Holidays.
 * Everything here is editable later from the admin panel (/admin).
 * Images are Unsplash photos (free for commercial use); swap them for your own any time.
 */
export const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

export type SeedDestination = {
  slug: string;
  name: string;
  country: string;
  region: "domestic" | "international";
  tagline: string;
  description: string;
  heroImage: string;
  lat: number;
  lng: number;
  bestTime: string;
  climate: string;
  visaInfo: string;
  highlights: string[];
  featured: boolean;
};

export type SeedPackage = {
  slug: string;
  title: string;
  destination: string;
  themes: string[];
  route: string[];
  durationDays: number;
  price: number;
  originalPrice?: number;
  offerDays?: number;
  coverImage: string;
  gallery: string[];
  summary: string;
  overview: string;
  highlights: string[];
  itinerary: ItineraryDay[];
  inclusions: string[];
  exclusions: string[];
  groupSizeMax: number;
  difficulty: "easy" | "moderate" | "challenging";
  featured?: boolean;
  popularity: number;
  /** Fixed-departure group tour: months (1-12) in which departures run. */
  groupSeason?: number[];
  seatsPerDeparture?: number;
};

export const seedDestinations: SeedDestination[] = [
  {
    slug: "kashmir",
    name: "Kashmir",
    country: "India",
    region: "domestic",
    tagline: "Paradise on Earth",
    description:
      "Shikaras gliding across Dal Lake, saffron fields, Mughal gardens and meadows that turn to snowfields in winter. Kashmir is poetry you can walk through.",
    heroImage: img("1595815771614-ade9d652a65d"),
    lat: 34.0837,
    lng: 74.7973,
    bestTime: "March – October (snow lovers: December – February)",
    climate: "Pleasant summers 15–30°C, snowy winters down to -5°C",
    visaInfo: "No visa needed for Indian citizens. Carry a government photo ID.",
    highlights: ["Dal Lake houseboats", "Gulmarg Gondola", "Betaab Valley", "Mughal Gardens"],
    featured: true,
  },
  {
    slug: "ladakh",
    name: "Ladakh",
    country: "India",
    region: "domestic",
    tagline: "The land of high passes",
    description:
      "Moonscapes, turquoise lakes and monasteries perched on cliffs. Ride the highest motorable roads on Earth and sleep under a sky full of stars.",
    heroImage: img("1626621341517-bbf3d9990a23"),
    lat: 34.1526,
    lng: 77.5771,
    bestTime: "May – September",
    climate: "Cold desert; 5–25°C in summer, very dry",
    visaInfo: "Inner Line Permit for Nubra, Pangong & Turtuk — we arrange it for you.",
    highlights: ["Pangong Tso", "Khardung La", "Nubra sand dunes", "Thiksey Monastery"],
    featured: true,
  },
  {
    slug: "himachal",
    name: "Himachal Pradesh",
    country: "India",
    region: "domestic",
    tagline: "Pine forests, apple orchards & snow",
    description:
      "From the colonial charm of Shimla to the adventure capital Manali and the stark beauty of Spiti, Himachal has a hill story for every traveller.",
    heroImage: img("1626015365107-338f0a7e2a43"),
    lat: 32.2432,
    lng: 77.1892,
    bestTime: "March – June, October – February for snow",
    climate: "Cool summers 10–25°C, snowfall in winter",
    visaInfo: "No visa needed for Indian citizens.",
    highlights: ["Solang Valley", "Rohtang / Atal Tunnel", "Mall Road Shimla", "Key Monastery"],
    featured: false,
  },
  {
    slug: "kerala",
    name: "Kerala",
    country: "India",
    region: "domestic",
    tagline: "God's own country",
    description:
      "Mist-wrapped tea estates, slow houseboat days on the backwaters, spice markets and Ayurveda by the sea — Kerala is India at its most serene.",
    heroImage: img("1602216056096-3b40cc0c9944"),
    lat: 9.4981,
    lng: 76.3388,
    bestTime: "September – March",
    climate: "Tropical; 23–32°C, monsoon June – August",
    visaInfo: "No visa needed for Indian citizens.",
    highlights: ["Alleppey houseboat", "Munnar tea gardens", "Periyar wildlife", "Kochi Fort"],
    featured: true,
  },
  {
    slug: "goa",
    name: "Goa",
    country: "India",
    region: "domestic",
    tagline: "Sun, sand & susegad",
    description:
      "Golden beaches, Portuguese lanes, beach shacks and sunsets that turn into all-night parties. Goa is the perfect long-weekend reset.",
    heroImage: img("1512343879784-a960bf40e7f2"),
    lat: 15.2993,
    lng: 74.124,
    bestTime: "November – February",
    climate: "Tropical; 24–33°C",
    visaInfo: "No visa needed for Indian citizens.",
    highlights: ["Baga & Calangute", "Fontainhas Latin Quarter", "Dudhsagar Falls", "Mandovi cruise"],
    featured: false,
  },
  {
    slug: "rajasthan",
    name: "Rajasthan",
    country: "India",
    region: "domestic",
    tagline: "Land of kings",
    description:
      "Forts that glow gold at sunset, palaces floating on lakes and desert camps under the stars. Rajasthan is royalty, colour and legend.",
    heroImage: img("1477587458883-47145ed94245"),
    lat: 26.9124,
    lng: 75.7873,
    bestTime: "October – March",
    climate: "Desert; pleasant winters 10–27°C",
    visaInfo: "No visa needed for Indian citizens.",
    highlights: ["Amber Fort", "Mehrangarh Fort", "Sam sand dunes", "Lake Pichola"],
    featured: true,
  },
  {
    slug: "golden-triangle",
    name: "Golden Triangle",
    country: "India",
    region: "domestic",
    tagline: "Delhi · Agra · Jaipur",
    description:
      "India's classic circuit: Mughal monuments, the eternal Taj Mahal at sunrise and the pink city of Jaipur — perfect for first-timers and families.",
    heroImage: img("1524492412937-b28074a5d7da"),
    lat: 27.1751,
    lng: 78.0421,
    bestTime: "October – March",
    climate: "Hot summers, pleasant winters 8–25°C",
    visaInfo: "No visa needed for Indian citizens.",
    highlights: ["Taj Mahal at sunrise", "Qutub Minar", "Hawa Mahal", "Fatehpur Sikri"],
    featured: false,
  },
  {
    slug: "andaman",
    name: "Andaman Islands",
    country: "India",
    region: "domestic",
    tagline: "India's tropical island escape",
    description:
      "Powder-white beaches, glass-clear water and coral reefs. Scuba dive at Havelock, watch the sunset at Radhanagar and sail between emerald islands.",
    heroImage: img("1506929562872-bb421503ef21"),
    lat: 11.6234,
    lng: 92.7265,
    bestTime: "October – May",
    climate: "Tropical; 23–31°C",
    visaInfo: "No visa needed for Indian citizens.",
    highlights: ["Radhanagar Beach", "Scuba at Havelock", "Cellular Jail light show", "Neil Island"],
    featured: true,
  },
  {
    slug: "sikkim-darjeeling",
    name: "Sikkim & Darjeeling",
    country: "India",
    region: "domestic",
    tagline: "Kanchenjunga sunrises",
    description:
      "Prayer flags, frozen lakes, toy trains and endless tea gardens with the world's third-highest peak watching over you.",
    heroImage: img("1544085311-11a028465b03"),
    lat: 27.3389,
    lng: 88.6065,
    bestTime: "March – June, October – December",
    climate: "Cool; 5–20°C",
    visaInfo: "Protected Area Permit for North Sikkim — arranged by us.",
    highlights: ["Tsomgo Lake", "Yumthang Valley", "Tiger Hill sunrise", "Toy Train ride"],
    featured: false,
  },
  {
    slug: "uttarakhand",
    name: "Uttarakhand",
    country: "India",
    region: "domestic",
    tagline: "Dev Bhoomi — land of the gods",
    description:
      "Sacred shrines high in the Himalaya, the Ganga's spiritual ghats in Rishikesh and Haridwar, and trails through rhododendron forests.",
    heroImage: img("1464822759023-fed622ff2c3b"),
    lat: 30.0869,
    lng: 78.2676,
    bestTime: "May – June, September – October",
    climate: "Mountain; 5–25°C during the Yatra season",
    visaInfo: "Char Dham Yatra registration required — we handle it.",
    highlights: ["Kedarnath", "Badrinath", "Ganga Aarti at Har Ki Pauri", "Rishikesh"],
    featured: false,
  },
  {
    slug: "dubai",
    name: "Dubai",
    country: "United Arab Emirates",
    region: "international",
    tagline: "The city of superlatives",
    description:
      "Sky-high towers, golden deserts, theme parks and world-class shopping. Dubai is glamour, adventure and family fun in one glittering city.",
    heroImage: img("1512453979798-5ea266f8880c"),
    lat: 25.2048,
    lng: 55.2708,
    bestTime: "November – March",
    climate: "Desert; 18–30°C in winter",
    visaInfo: "E-visa for Indians (approx. 3–5 working days) — included in our packages.",
    highlights: ["Burj Khalifa", "Desert safari", "Dubai Marina cruise", "Abu Dhabi Grand Mosque"],
    featured: true,
  },
  {
    slug: "thailand",
    name: "Thailand",
    country: "Thailand",
    region: "international",
    tagline: "The land of smiles",
    description:
      "Golden temples, floating markets, limestone islands and street food that will ruin all other food for you. Thailand is the ultimate first international trip.",
    heroImage: img("1552465011-b4e21bf6e79a"),
    lat: 13.7563,
    lng: 100.5018,
    bestTime: "November – April",
    climate: "Tropical; 25–33°C",
    visaInfo: "Visa-free / visa on arrival for Indian passport holders (check latest rules before travel).",
    highlights: ["Phi Phi Islands", "Grand Palace", "Coral Island", "Night markets"],
    featured: true,
  },
  {
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    region: "international",
    tagline: "Island of the gods",
    description:
      "Emerald rice terraces, cliff-top temples, jungle swings and private pool villas. Bali is made for honeymooners and dreamers.",
    heroImage: img("1537996194471-e657df975ab4"),
    lat: -8.3405,
    lng: 115.092,
    bestTime: "April – October",
    climate: "Tropical; 24–31°C",
    visaInfo: "Visa on arrival for Indians (approx. IDR 500,000).",
    highlights: ["Ubud rice terraces", "Uluwatu temple", "Nusa Penida", "Mount Batur sunrise"],
    featured: true,
  },
  {
    slug: "maldives",
    name: "Maldives",
    country: "Maldives",
    region: "international",
    tagline: "Overwater luxury",
    description:
      "Wake up above a turquoise lagoon, snorkel with turtles and dine on a sandbank. The Maldives is the ultimate barefoot-luxury escape.",
    heroImage: img("1514282401047-d79a71a590e8"),
    lat: 3.2028,
    lng: 73.2207,
    bestTime: "November – April",
    climate: "Tropical; 26–31°C",
    visaInfo: "Free 30-day visa on arrival for Indian citizens.",
    highlights: ["Water villa stay", "Snorkelling reefs", "Sandbank dinner", "Seaplane transfer"],
    featured: true,
  },
  {
    slug: "singapore-malaysia",
    name: "Singapore & Malaysia",
    country: "Singapore · Malaysia",
    region: "international",
    tagline: "Two countries, endless fun",
    description:
      "Universal Studios, Gardens by the Bay, Petronas Towers and Genting Highlands — a perfectly paced combo for families.",
    heroImage: img("1525625293386-3f8f99389edd"),
    lat: 1.3521,
    lng: 103.8198,
    bestTime: "February – April",
    climate: "Tropical; 25–32°C",
    visaInfo: "E-visa for Singapore; Malaysia visa-free for Indians (check latest rules).",
    highlights: ["Universal Studios", "Gardens by the Bay", "Sentosa", "Petronas Towers"],
    featured: false,
  },
  {
    slug: "europe",
    name: "Europe",
    country: "France · Switzerland · Italy",
    region: "international",
    tagline: "Alps, art & la dolce vita",
    description:
      "The Eiffel Tower at night, snow-capped Swiss peaks, gondolas in Venice and the Colosseum in Rome — Europe's greatest hits on one unforgettable journey.",
    heroImage: img("1530122037265-a5f1f91d3b99"),
    lat: 46.8182,
    lng: 8.2275,
    bestTime: "April – October",
    climate: "Temperate; 12–28°C in season",
    visaInfo: "Schengen visa required — our visa desk helps with documentation & appointments.",
    highlights: ["Eiffel Tower", "Jungfraujoch", "Venice gondola", "Colosseum"],
    featured: true,
  },
  {
    slug: "vietnam",
    name: "Vietnam",
    country: "Vietnam",
    region: "international",
    tagline: "Lanterns, limestone & pho",
    description:
      "Cruise Ha Long Bay's emerald waters, wander lantern-lit Hoi An and eat your way through Hanoi's Old Quarter.",
    heroImage: img("1528127269322-539801943592"),
    lat: 21.0285,
    lng: 105.8542,
    bestTime: "October – April",
    climate: "Varies north to south; 18–32°C",
    visaInfo: "E-visa for Indians (approx. 3 working days).",
    highlights: ["Ha Long Bay cruise", "Hoi An Ancient Town", "Golden Bridge", "Cu Chi tunnels"],
    featured: false,
  },
  {
    slug: "japan",
    name: "Japan",
    country: "Japan",
    region: "international",
    tagline: "Where tradition meets tomorrow",
    description:
      "Bullet trains and bamboo forests, neon nights in Tokyo and quiet temples in Kyoto, framed by Mount Fuji and clouds of cherry blossom.",
    heroImage: img("1493976040374-85c8e12f0c0e"),
    lat: 35.6762,
    lng: 139.6503,
    bestTime: "March – May, October – November",
    climate: "Temperate; 10–24°C in spring & autumn",
    visaInfo: "Visa required (e-visa available for Indians) — our visa desk assists.",
    highlights: ["Mount Fuji", "Kyoto temples", "Shibuya crossing", "Bullet train ride"],
    featured: true,
  },
  {
    slug: "bhutan",
    name: "Bhutan",
    country: "Bhutan",
    region: "international",
    tagline: "The land of happiness",
    description:
      "Cliffside monasteries, prayer-flag passes and a kingdom that measures success in happiness. Bhutan is calm you will carry home.",
    heroImage: img("1553856622-d1b352e9a211"),
    lat: 27.5142,
    lng: 90.4336,
    bestTime: "March – May, September – November",
    climate: "Mountain; 8–22°C",
    visaInfo: "No visa for Indian citizens; entry permit + SDF apply — handled by us.",
    highlights: ["Tiger's Nest Monastery", "Punakha Dzong", "Dochula Pass", "Buddha Dordenma"],
    featured: false,
  },
];

const stdIncl = [
  "Hand-picked hotels with daily breakfast",
  "All transfers & sightseeing in a private vehicle",
  "Dedicated trip coordinator, 24×7 on WhatsApp",
  "All applicable tolls, parking & driver allowances",
];

const intlIncl = [
  "Return economy airfare from major Indian metros",
  "Tourist visa & travel insurance",
  "4★ hotels with daily breakfast",
  "Airport transfers & sightseeing as per itinerary",
  "English-speaking local guide",
];

const stdExcl = [
  "Lunch & dinner unless mentioned",
  "Entry tickets not mentioned in inclusions",
  "Personal expenses, tips & porterage",
  "Anything not listed under inclusions",
];

export const seedPackages: SeedPackage[] = [
  {
    slug: "kashmir-paradise-on-earth",
    title: "Kashmir: Paradise on Earth",
    destination: "kashmir",
    themes: ["honeymoon", "family", "nature"],
    route: ["Srinagar", "Gulmarg", "Pahalgam", "Sonmarg"],
    durationDays: 6,
    price: 24999,
    originalPrice: 31999,
    offerDays: 6,
    coverImage: img("1595815771614-ade9d652a65d"),
    gallery: [img("1501785888041-af3ef285b470"), img("1464822759023-fed622ff2c3b"), img("1469474968028-56623f02e42e")],
    summary: "Houseboat nights on Dal Lake, the Gulmarg gondola and the valleys of Pahalgam.",
    overview:
      "This is the Kashmir everyone dreams of. Begin with a night aboard a hand-carved houseboat on Dal Lake, ride one of the world's highest cable cars in Gulmarg, walk the pine-scented valleys of Pahalgam and stand before the Thajiwas glacier in Sonmarg. Unhurried pacing, a private car and hand-picked stays make it ideal for couples and families alike.",
    highlights: [
      "Night on a premium Dal Lake houseboat",
      "Sunset shikara ride with kahwa",
      "Gulmarg Gondola (Phase 1) tickets included",
      "Betaab, Aru & Chandanwari valleys",
      "Mughal gardens: Nishat & Shalimar",
    ],
    itinerary: [
      { day: 1, title: "Arrive Srinagar · Houseboat welcome", description: "Meet your driver at Srinagar airport and check in to your houseboat. Evening shikara ride across Dal Lake past floating gardens and markets.", meals: "Dinner", stay: "Deluxe houseboat, Dal Lake" },
      { day: 2, title: "Srinagar → Gulmarg", description: "Drive through apple orchards to Gulmarg, the meadow of flowers. Ride the Gondola to Kongdoori with views of the Pir Panjal range.", meals: "Breakfast, Dinner", stay: "Hotel in Gulmarg", activities: ["Gondola ride", "Pony ride (optional)"] },
      { day: 3, title: "Gulmarg → Pahalgam", description: "Scenic drive to Pahalgam via saffron fields of Pampore and the Avantipura ruins. Evening by the Lidder river.", meals: "Breakfast, Dinner", stay: "Riverside hotel, Pahalgam" },
      { day: 4, title: "Pahalgam valleys", description: "Explore Betaab Valley, Aru Valley and Chandanwari in a local union cab. Picnic lunch on the meadows.", meals: "Breakfast, Dinner", stay: "Riverside hotel, Pahalgam" },
      { day: 5, title: "Sonmarg day trip · Srinagar", description: "Day excursion to Sonmarg, the meadow of gold, and the Thajiwas glacier. Return to Srinagar for Mughal gardens.", meals: "Breakfast, Dinner", stay: "Hotel in Srinagar" },
      { day: 6, title: "Departure", description: "Breakfast, last-minute shopping for pashmina and dry fruits, and transfer to the airport.", meals: "Breakfast" },
    ],
    inclusions: [...stdIncl, "1 night deluxe houseboat", "Shikara ride & Gulmarg Gondola Phase 1"],
    exclusions: [...stdExcl, "Airfare to Srinagar", "Local union cabs in Pahalgam / Sonmarg sledges"],
    groupSizeMax: 8,
    difficulty: "easy",
    featured: true,
    popularity: 98,
  },
  {
    slug: "leh-ladakh-bike-expedition",
    title: "Leh Ladakh Bike Expedition",
    destination: "ladakh",
    themes: ["adventure", "group", "friends"],
    route: ["Leh", "Khardung La", "Nubra", "Turtuk", "Pangong Tso"],
    durationDays: 9,
    price: 34999,
    originalPrice: 39999,
    coverImage: img("1626621341517-bbf3d9990a23"),
    gallery: [img("1519681393784-d120267933ba"), img("1506905925346-21bda4d32df4"), img("1454496522488-7a8e488e8606")],
    summary: "Ride Royal Enfields over the world's highest passes with a backup vehicle & mechanic.",
    overview:
      "The ride of a lifetime. Acclimatise in Leh, then twist the throttle over Khardung La, camp among the dunes of Nubra, visit the frontier village of Turtuk and sleep beside the impossibly blue Pangong Tso. Our road captain, mechanic and backup SUV ride with you every kilometre.",
    highlights: [
      "Royal Enfield Himalayan 411cc with fuel",
      "Road captain, mechanic & backup vehicle",
      "Camps at Nubra & Pangong",
      "Inner Line Permits handled",
      "Oxygen cylinders & first-aid on board",
    ],
    itinerary: [
      { day: 1, title: "Arrive Leh · Acclimatise", description: "Airport pick-up and complete rest to acclimatise to 3,500 m. Evening briefing and bike allotment.", meals: "Dinner", stay: "Hotel in Leh" },
      { day: 2, title: "Leh local ride", description: "Short acclimatisation ride to Hall of Fame, Magnetic Hill, Gurudwara Pathar Sahib and the Indus–Zanskar confluence.", meals: "Breakfast, Dinner", stay: "Hotel in Leh" },
      { day: 3, title: "Leh → Khardung La → Nubra", description: "Ride over Khardung La (5,359 m) and descend into Nubra. Bactrian camel ride at the Hunder dunes.", meals: "Breakfast, Dinner", stay: "Swiss camp, Hunder" },
      { day: 4, title: "Nubra → Turtuk → Nubra", description: "Follow the Shyok river to Turtuk, a Balti village opened to travellers only in 2010. Apricot orchards and local lunch.", meals: "Breakfast, Dinner", stay: "Swiss camp, Hunder" },
      { day: 5, title: "Nubra → Pangong Tso via Shyok", description: "Ride the rugged Shyok route to Pangong Tso. Watch the lake change colours at sunset.", meals: "Breakfast, Dinner", stay: "Lakeside camp, Pangong" },
      { day: 6, title: "Pangong → Chang La → Leh", description: "Sunrise at the lake, then ride over Chang La (5,360 m) back to Leh. Celebration dinner.", meals: "Breakfast, Dinner", stay: "Hotel in Leh" },
      { day: 7, title: "Leh → Sham Valley", description: "Ride to Likir, Alchi and the apricot villages of Sham Valley. Optional rafting on the Zanskar.", meals: "Breakfast, Dinner", stay: "Hotel in Leh" },
      { day: 8, title: "Monastery trail", description: "Thiksey, Hemis and Shey monasteries. Free evening at Leh market.", meals: "Breakfast, Dinner", stay: "Hotel in Leh" },
      { day: 9, title: "Departure", description: "Bike handover and airport drop with memories (and photos) for life.", meals: "Breakfast" },
    ],
    inclusions: ["Royal Enfield Himalayan with fuel", "Road captain, mechanic & backup SUV", "Hotels & camps on twin sharing with breakfast & dinner", "Inner Line Permits & environment fees", "Oxygen cylinder & first-aid kit"],
    exclusions: ["Airfare to Leh", "Riding gear (available on rent)", "Bike damage costs", "Pillion supplement", "Lunches"],
    groupSizeMax: 16,
    difficulty: "challenging",
    featured: true,
    popularity: 95,
    groupSeason: [5, 6, 7, 8, 9],
    seatsPerDeparture: 16,
  },
  {
    slug: "spiti-valley-expedition",
    title: "Spiti Valley Road Expedition",
    destination: "himachal",
    themes: ["adventure", "group", "nature"],
    route: ["Shimla", "Kalpa", "Tabo", "Kaza", "Chandratal", "Manali"],
    durationDays: 8,
    price: 27999,
    coverImage: img("1454496522488-7a8e488e8606"),
    gallery: [img("1506905925346-21bda4d32df4"), img("1519681393784-d120267933ba"), img("1500530855697-b586d89ba3ee")],
    summary: "A full circuit through the 'middle land' — ancient monasteries, fossil villages and Chandratal.",
    overview:
      "Spiti is raw, remote and utterly unforgettable. This road expedition runs the full circuit from Shimla through Kinnaur's apple country to the 1,000-year-old Tabo monastery, the world's highest post office at Hikkim and the crescent moon lake of Chandratal, exiting via Kunzum Pass to Manali.",
    highlights: ["Key, Tabo & Dhankar monasteries", "Hikkim — world's highest post office", "Camping at Chandratal", "Kunzum & Rohtang passes"],
    itinerary: [
      { day: 1, title: "Shimla → Kalpa", description: "Drive along the Sutlej into Kinnaur. Views of the Kinner Kailash range from Kalpa.", meals: "Dinner", stay: "Hotel in Kalpa" },
      { day: 2, title: "Kalpa → Tabo", description: "Cross into Spiti via Nako lake and the dramatic Malling Nallah stretch.", meals: "Breakfast, Dinner", stay: "Homestay in Tabo" },
      { day: 3, title: "Tabo → Dhankar → Kaza", description: "Visit Tabo monastery's ancient murals and the clifftop Dhankar monastery.", meals: "Breakfast, Dinner", stay: "Hotel in Kaza" },
      { day: 4, title: "Villages above the clouds", description: "Hikkim, Komic and Langza — post a letter from 4,400 m and hunt for fossils.", meals: "Breakfast, Dinner", stay: "Hotel in Kaza" },
      { day: 5, title: "Key Monastery & Kibber", description: "The iconic Key monastery and Chicham bridge, Asia's highest suspension bridge.", meals: "Breakfast, Dinner", stay: "Hotel in Kaza" },
      { day: 6, title: "Kaza → Chandratal", description: "Cross Kunzum Pass to the crescent-shaped Chandratal lake. Night under a blanket of stars.", meals: "Breakfast, Dinner", stay: "Camp at Chandratal" },
      { day: 7, title: "Chandratal → Manali", description: "Drive via Batal and the Atal Tunnel to Manali. Farewell dinner in Old Manali.", meals: "Breakfast, Dinner", stay: "Hotel in Manali" },
      { day: 8, title: "Departure", description: "Breakfast and onward journey from Manali.", meals: "Breakfast" },
    ],
    inclusions: ["Tempo Traveller / SUV for the whole circuit", "Stays on twin/triple sharing with breakfast & dinner", "Experienced trip captain", "Permits & first-aid with oxygen"],
    exclusions: ["Travel to Shimla & from Manali", "Lunches", "Personal expenses"],
    groupSizeMax: 14,
    difficulty: "challenging",
    popularity: 80,
    groupSeason: [6, 7, 8, 9, 10],
    seatsPerDeparture: 14,
  },
  {
    slug: "shimla-manali-delight",
    title: "Shimla Manali Delight",
    destination: "himachal",
    themes: ["family", "honeymoon", "nature"],
    route: ["Shimla", "Kufri", "Manali", "Solang"],
    durationDays: 6,
    price: 18499,
    originalPrice: 21999,
    offerDays: 3,
    coverImage: img("1626015365107-338f0a7e2a43"),
    gallery: [img("1464822759023-fed622ff2c3b"), img("1501785888041-af3ef285b470"), img("1469474968028-56623f02e42e")],
    summary: "The classic Himachal holiday: Mall Road strolls, Solang Valley snow and riverside cafés.",
    overview:
      "A perfectly paced first hill holiday. Ride the toy-train era charm of Shimla, play in the snow at Kufri and Solang, cross the Atal Tunnel to Sissu and unwind in the cafés of Old Manali beside the Beas river.",
    highlights: ["Mall Road & The Ridge", "Solang Valley snow activities", "Atal Tunnel & Sissu", "Hadimba Temple & Old Manali"],
    itinerary: [
      { day: 1, title: "Chandigarh → Shimla", description: "Pick-up from Chandigarh and drive to Shimla. Evening walk on Mall Road and The Ridge.", meals: "Dinner", stay: "Hotel in Shimla" },
      { day: 2, title: "Kufri & Shimla sights", description: "Kufri's apple orchards and snow point, then Jakhoo Temple and Christ Church.", meals: "Breakfast, Dinner", stay: "Hotel in Shimla" },
      { day: 3, title: "Shimla → Manali", description: "Scenic drive along the Beas via Kullu, with a stop for river rafting (optional).", meals: "Breakfast, Dinner", stay: "Hotel in Manali" },
      { day: 4, title: "Solang Valley & Atal Tunnel", description: "Snow activities at Solang and a drive through the Atal Tunnel to Sissu waterfall.", meals: "Breakfast, Dinner", stay: "Hotel in Manali", activities: ["Paragliding (optional)", "Skiing (season)"] },
      { day: 5, title: "Manali local", description: "Hadimba Temple, Vashisht hot springs, Tibetan monastery and Old Manali cafés.", meals: "Breakfast, Dinner", stay: "Hotel in Manali" },
      { day: 6, title: "Departure", description: "Drive back to Chandigarh for your onward journey.", meals: "Breakfast" },
    ],
    inclusions: stdIncl,
    exclusions: [...stdExcl, "Snow activities & paragliding", "Rohtang permit (if applicable)"],
    groupSizeMax: 10,
    difficulty: "easy",
    popularity: 90,
  },
  {
    slug: "kerala-gods-own-country",
    title: "Kerala: God's Own Country",
    destination: "kerala",
    themes: ["honeymoon", "family", "nature", "wellness"],
    route: ["Kochi", "Munnar", "Thekkady", "Alleppey"],
    durationDays: 6,
    price: 21999,
    originalPrice: 25999,
    coverImage: img("1602216056096-3b40cc0c9944"),
    gallery: [img("1593693397690-362cb9666fc2"), img("1469474968028-56623f02e42e"), img("1501785888041-af3ef285b470")],
    summary: "Tea hills, spice plantations and a private houseboat on the backwaters.",
    overview:
      "Kerala slows your pulse. Wander Fort Kochi's Chinese fishing nets, wake to mist in Munnar's tea gardens, take a spice walk and bamboo raft in Thekkady and float through palm-fringed backwaters on your own private houseboat with a chef on board.",
    highlights: ["Private houseboat with all meals", "Munnar tea museum & Eravikulam", "Periyar boat safari", "Kathakali performance"],
    itinerary: [
      { day: 1, title: "Arrive Kochi", description: "Fort Kochi heritage walk, Chinese fishing nets and an evening Kathakali show.", meals: "Dinner", stay: "Heritage hotel, Fort Kochi" },
      { day: 2, title: "Kochi → Munnar", description: "Drive into the Western Ghats past Cheeyappara and Valara waterfalls.", meals: "Breakfast, Dinner", stay: "Resort in Munnar" },
      { day: 3, title: "Munnar", description: "Eravikulam National Park, tea museum, Mattupetty dam and Echo Point.", meals: "Breakfast, Dinner", stay: "Resort in Munnar" },
      { day: 4, title: "Munnar → Thekkady", description: "Spice plantation walk and a boat safari on Periyar lake to spot elephants.", meals: "Breakfast, Dinner", stay: "Jungle resort, Thekkady" },
      { day: 5, title: "Thekkady → Alleppey houseboat", description: "Board your private houseboat and cruise the backwaters with fresh Kerala meals cooked on board.", meals: "All meals", stay: "Private houseboat" },
      { day: 6, title: "Departure", description: "Disembark after breakfast and transfer to Kochi airport.", meals: "Breakfast" },
    ],
    inclusions: [...stdIncl, "Private AC houseboat with all meals", "Periyar boat safari"],
    exclusions: [...stdExcl, "Ayurvedic spa treatments"],
    groupSizeMax: 10,
    difficulty: "easy",
    featured: true,
    popularity: 93,
  },
  {
    slug: "goa-beach-escape",
    title: "Goa Beach & Nightlife Escape",
    destination: "goa",
    themes: ["beach", "friends", "weekend"],
    route: ["North Goa", "Panjim", "South Goa"],
    durationDays: 4,
    price: 12999,
    originalPrice: 15499,
    offerDays: 2,
    coverImage: img("1512343879784-a960bf40e7f2"),
    gallery: [img("1507525428034-b723cf961d3e"), img("1506929562872-bb421503ef21"), img("1544551763-46a013bb70d5")],
    summary: "Beach-hopping, a sunset cruise, water sports and the best of Goa's nightlife.",
    overview:
      "Four days, zero stress. Stay steps from the sand in North Goa, hop between Baga, Anjuna and Vagator, explore the Latin Quarter of Fontainhas, cruise the Mandovi at sunset and escape to the quiet beaches of the south.",
    highlights: ["Beachside resort with pool", "Sunset cruise on the Mandovi", "Water sports combo", "Old Goa churches (UNESCO)"],
    itinerary: [
      { day: 1, title: "Arrive Goa", description: "Check in to your beach resort. Sunset at Vagator and dinner at a beach shack.", meals: "—", stay: "Resort in North Goa" },
      { day: 2, title: "North Goa beaches", description: "Fort Aguada, Baga, Calangute and Anjuna flea market. Water sports combo at Calangute.", meals: "Breakfast", stay: "Resort in North Goa", activities: ["Parasailing", "Jet ski", "Banana ride"] },
      { day: 3, title: "Heritage & cruise", description: "Basilica of Bom Jesus, Fontainhas Latin Quarter and a sunset cruise on the Mandovi with live music.", meals: "Breakfast", stay: "Resort in North Goa" },
      { day: 4, title: "South Goa & departure", description: "Colva and Palolem beaches before your airport drop.", meals: "Breakfast" },
    ],
    inclusions: ["3 nights beach resort with breakfast", "Airport transfers", "North Goa & South Goa sightseeing", "Water sports combo", "Mandovi sunset cruise"],
    exclusions: stdExcl,
    groupSizeMax: 12,
    difficulty: "easy",
    popularity: 88,
  },
  {
    slug: "royal-rajasthan",
    title: "Royal Rajasthan",
    destination: "rajasthan",
    themes: ["culture", "family", "luxury"],
    route: ["Jaipur", "Jodhpur", "Jaisalmer", "Udaipur"],
    durationDays: 8,
    price: 32999,
    originalPrice: 38999,
    coverImage: img("1477587458883-47145ed94245"),
    gallery: [img("1599661046289-e31897846e41"), img("1524492412937-b28074a5d7da"), img("1451337516015-6b6e9a44a8a3")],
    summary: "Forts, palaces and a night in a luxury desert camp across four royal cities.",
    overview:
      "Live like royalty across Rajasthan's four great cities. Explore Amber Fort and the Pink City, the blue lanes of Jodhpur beneath Mehrangarh, a golden sunset on the Sam dunes with folk music around the fire, and the romance of Udaipur's lake palaces.",
    highlights: ["Heritage haveli stays", "Desert camp with folk night", "Camel safari on Sam dunes", "Lake Pichola boat ride"],
    itinerary: [
      { day: 1, title: "Arrive Jaipur", description: "Check in to a heritage hotel. Evening at Chokhi Dhani village for Rajasthani dinner and folk dances.", meals: "Dinner", stay: "Heritage hotel, Jaipur" },
      { day: 2, title: "Jaipur", description: "Amber Fort, Hawa Mahal, City Palace and Jantar Mantar. Shopping for block prints and gems.", meals: "Breakfast", stay: "Heritage hotel, Jaipur" },
      { day: 3, title: "Jaipur → Jodhpur", description: "Drive to the Blue City. Sunset at Jaswant Thada.", meals: "Breakfast", stay: "Hotel in Jodhpur" },
      { day: 4, title: "Jodhpur → Jaisalmer", description: "Mehrangarh Fort in the morning, then onward to the Golden City.", meals: "Breakfast", stay: "Hotel in Jaisalmer" },
      { day: 5, title: "Jaisalmer & the dunes", description: "Living fort, Patwon ki Haveli, then camel safari at Sam dunes and a night at a luxury desert camp.", meals: "Breakfast, Dinner", stay: "Luxury desert camp" },
      { day: 6, title: "Jaisalmer → Udaipur", description: "Long scenic drive (or optional flight) to the City of Lakes.", meals: "Breakfast", stay: "Lake-view hotel, Udaipur" },
      { day: 7, title: "Udaipur", description: "City Palace, Saheliyon ki Bari and a sunset boat ride on Lake Pichola.", meals: "Breakfast", stay: "Lake-view hotel, Udaipur" },
      { day: 8, title: "Departure", description: "Airport or railway station drop.", meals: "Breakfast" },
    ],
    inclusions: [...stdIncl, "Desert camp with dinner & cultural night", "Camel safari", "Lake Pichola boat ride"],
    exclusions: [...stdExcl, "Monument entry fees"],
    groupSizeMax: 10,
    difficulty: "easy",
    featured: true,
    popularity: 86,
  },
  {
    slug: "golden-triangle-tour",
    title: "Golden Triangle: Delhi, Agra & Jaipur",
    destination: "golden-triangle",
    themes: ["culture", "family"],
    route: ["Delhi", "Agra", "Fatehpur Sikri", "Jaipur"],
    durationDays: 5,
    price: 16999,
    coverImage: img("1524492412937-b28074a5d7da"),
    gallery: [img("1599661046289-e31897846e41"), img("1477587458883-47145ed94245"), img("1488646953014-85cb44e25828")],
    summary: "The Taj Mahal at sunrise, Mughal Delhi and the Pink City in five easy days.",
    overview:
      "India's most iconic circuit, done right. A local expert guides you through Old and New Delhi, you watch the sun rise over the Taj Mahal, explore the abandoned Mughal capital of Fatehpur Sikri and finish among the forts and bazaars of Jaipur.",
    highlights: ["Taj Mahal at sunrise", "Rickshaw ride in Chandni Chowk", "Fatehpur Sikri", "Amber Fort"],
    itinerary: [
      { day: 1, title: "Delhi", description: "Qutub Minar, Humayun's Tomb, India Gate and a rickshaw ride through Chandni Chowk.", meals: "Dinner", stay: "Hotel in Delhi" },
      { day: 2, title: "Delhi → Agra", description: "Expressway drive to Agra. Agra Fort and sunset at Mehtab Bagh facing the Taj.", meals: "Breakfast", stay: "Hotel in Agra" },
      { day: 3, title: "Taj sunrise → Jaipur", description: "Taj Mahal at sunrise, then Fatehpur Sikri en route to Jaipur.", meals: "Breakfast", stay: "Hotel in Jaipur" },
      { day: 4, title: "Jaipur", description: "Amber Fort, Hawa Mahal, City Palace and the bazaars of the Pink City.", meals: "Breakfast", stay: "Hotel in Jaipur" },
      { day: 5, title: "Departure", description: "Drive back to Delhi or drop at Jaipur airport.", meals: "Breakfast" },
    ],
    inclusions: [...stdIncl, "Licensed guide in Delhi, Agra & Jaipur"],
    exclusions: [...stdExcl, "Monument entry fees"],
    groupSizeMax: 12,
    difficulty: "easy",
    popularity: 78,
  },
  {
    slug: "andaman-island-hopping",
    title: "Andaman Island Hopping",
    destination: "andaman",
    themes: ["beach", "honeymoon", "adventure"],
    route: ["Port Blair", "Havelock", "Neil Island"],
    durationDays: 6,
    price: 29999,
    originalPrice: 34999,
    offerDays: 5,
    coverImage: img("1506929562872-bb421503ef21"),
    gallery: [img("1544551763-46a013bb70d5"), img("1507525428034-b723cf961d3e"), img("1514282401047-d79a71a590e8")],
    summary: "Scuba at Havelock, sunset at Radhanagar and the quiet lagoons of Neil Island.",
    overview:
      "Island time, the Indian way. Ferry between Port Blair, Havelock and Neil, try a beginner scuba dive (no swimming needed), walk Asia's most celebrated beach at sunset and watch history come alive at the Cellular Jail light & sound show.",
    highlights: ["Beginner scuba dive at Havelock", "Radhanagar Beach sunset", "Premium ferries between islands", "Natural Bridge at Neil"],
    itinerary: [
      { day: 1, title: "Arrive Port Blair", description: "Corbyn's Cove beach and the Cellular Jail light & sound show.", meals: "Dinner", stay: "Hotel in Port Blair" },
      { day: 2, title: "Port Blair → Havelock", description: "Premium ferry to Havelock. Sunset at Radhanagar Beach.", meals: "Breakfast, Dinner", stay: "Beach resort, Havelock" },
      { day: 3, title: "Havelock · Scuba day", description: "Beginner scuba dive at Nemo Reef or Elephant Beach snorkelling.", meals: "Breakfast, Dinner", stay: "Beach resort, Havelock", activities: ["Scuba dive", "Glass-bottom boat"] },
      { day: 4, title: "Havelock → Neil Island", description: "Ferry to Neil. Laxmanpur beach sunset and the Natural Bridge rock formation.", meals: "Breakfast, Dinner", stay: "Resort in Neil" },
      { day: 5, title: "Neil → Port Blair", description: "Bharatpur beach morning, ferry back and Ross Island visit.", meals: "Breakfast, Dinner", stay: "Hotel in Port Blair" },
      { day: 6, title: "Departure", description: "Airport transfer.", meals: "Breakfast" },
    ],
    inclusions: [...stdIncl, "Premium ferry tickets", "1 beginner scuba dive", "Forest & entry permits"],
    exclusions: [...stdExcl, "Airfare to Port Blair"],
    groupSizeMax: 10,
    difficulty: "easy",
    featured: true,
    popularity: 84,
  },
  {
    slug: "sikkim-darjeeling-trail",
    title: "Sikkim & Darjeeling Himalayan Trail",
    destination: "sikkim-darjeeling",
    themes: ["family", "nature", "honeymoon"],
    route: ["Gangtok", "Lachung", "Yumthang", "Pelling", "Darjeeling"],
    durationDays: 7,
    price: 23999,
    coverImage: img("1544085311-11a028465b03"),
    gallery: [img("1469474968028-56623f02e42e"), img("1464822759023-fed622ff2c3b"), img("1506905925346-21bda4d32df4")],
    summary: "Frozen lakes, the valley of flowers and a Tiger Hill sunrise over Kanchenjunga.",
    overview:
      "The Eastern Himalaya at their most beautiful. Visit Tsomgo Lake and Baba Mandir, drive north to the rhododendron valley of Yumthang, see Kanchenjunga from Pelling's skywalk and catch the first light from Tiger Hill before a ride on the Darjeeling toy train.",
    highlights: ["Tsomgo Lake & Nathula (permit)", "Yumthang Valley & Zero Point", "Pelling skywalk", "Tiger Hill sunrise & toy train"],
    itinerary: [
      { day: 1, title: "Bagdogra → Gangtok", description: "Pick-up and drive along the Teesta river to Gangtok. Evening on MG Marg.", meals: "Dinner", stay: "Hotel in Gangtok" },
      { day: 2, title: "Tsomgo Lake & Baba Mandir", description: "Excursion to the glacial Tsomgo Lake and Baba Harbhajan Singh Mandir.", meals: "Breakfast, Dinner", stay: "Hotel in Gangtok" },
      { day: 3, title: "Gangtok → Lachung", description: "Drive north past Seven Sisters waterfall to the mountain village of Lachung.", meals: "All meals", stay: "Lodge in Lachung" },
      { day: 4, title: "Yumthang → Gangtok", description: "Yumthang Valley of Flowers and Zero Point (snow), then back to Gangtok.", meals: "Breakfast, Dinner", stay: "Hotel in Gangtok" },
      { day: 5, title: "Gangtok → Pelling", description: "Drive to Pelling; Rabdentse ruins and the Chenrezig skywalk.", meals: "Breakfast, Dinner", stay: "Hotel in Pelling" },
      { day: 6, title: "Pelling → Darjeeling", description: "Drive to Darjeeling via tea estates. Mall Road evening.", meals: "Breakfast, Dinner", stay: "Hotel in Darjeeling" },
      { day: 7, title: "Tiger Hill · Departure", description: "Tiger Hill sunrise, Batasia Loop, toy train joy ride, then drop at Bagdogra.", meals: "Breakfast" },
    ],
    inclusions: [...stdIncl, "North Sikkim permits", "Toy train joy ride"],
    exclusions: [...stdExcl, "Nathula Pass permit & vehicle"],
    groupSizeMax: 10,
    difficulty: "moderate",
    popularity: 74,
  },
  {
    slug: "char-dham-yatra",
    title: "Char Dham Yatra",
    destination: "uttarakhand",
    themes: ["pilgrimage", "group", "family"],
    route: ["Haridwar", "Yamunotri", "Gangotri", "Kedarnath", "Badrinath"],
    durationDays: 11,
    price: 42999,
    coverImage: img("1464822759023-fed622ff2c3b"),
    gallery: [img("1454496522488-7a8e488e8606"), img("1506905925346-21bda4d32df4"), img("1519681393784-d120267933ba")],
    summary: "A guided group pilgrimage to all four sacred dhams with registration & VIP darshan help.",
    overview:
      "Complete the most sacred journey in the Himalaya with care and comfort. Our yatra team handles registration, helicopter / pony bookings on request, medical checks and hotel stays near each shrine, while a group leader and pandit-ji guide you through the rituals at Yamunotri, Gangotri, Kedarnath and Badrinath.",
    highlights: ["All four dhams with group leader", "Ganga Aarti at Har Ki Pauri", "Yatra registration handled", "Doctor on call & oxygen in vehicles"],
    itinerary: [
      { day: 1, title: "Haridwar", description: "Arrive Haridwar and attend the evening Ganga Aarti at Har Ki Pauri.", meals: "Dinner", stay: "Hotel in Haridwar" },
      { day: 2, title: "Haridwar → Barkot", description: "Drive via Mussoorie and Kempty Falls to Barkot.", meals: "Breakfast, Dinner", stay: "Hotel in Barkot" },
      { day: 3, title: "Yamunotri darshan", description: "Drive to Janki Chatti and trek (6 km) or pony to Yamunotri temple. Holy dip in Surya Kund.", meals: "Breakfast, Dinner", stay: "Hotel in Barkot" },
      { day: 4, title: "Barkot → Uttarkashi", description: "Drive to Uttarkashi and visit the Kashi Vishwanath temple.", meals: "Breakfast, Dinner", stay: "Hotel in Uttarkashi" },
      { day: 5, title: "Gangotri darshan", description: "Day trip to Gangotri via Harsil valley. Darshan and return.", meals: "Breakfast, Dinner", stay: "Hotel in Uttarkashi" },
      { day: 6, title: "Uttarkashi → Guptkashi", description: "Long scenic drive along the Mandakini to Guptkashi.", meals: "Breakfast, Dinner", stay: "Hotel in Guptkashi" },
      { day: 7, title: "Kedarnath", description: "Drive to Gaurikund and trek / pony / helicopter (extra) to Kedarnath. Evening aarti.", meals: "Breakfast, Dinner", stay: "Camp / lodge at Kedarnath" },
      { day: 8, title: "Kedarnath → Guptkashi", description: "Morning darshan and descend to Guptkashi.", meals: "Breakfast, Dinner", stay: "Hotel in Guptkashi" },
      { day: 9, title: "Guptkashi → Badrinath", description: "Drive via Joshimath to Badrinath. Evening darshan and Tapt Kund.", meals: "Breakfast, Dinner", stay: "Hotel in Badrinath" },
      { day: 10, title: "Mana village → Rudraprayag", description: "Visit Mana, the last Indian village, and drive to Rudraprayag.", meals: "Breakfast, Dinner", stay: "Hotel in Rudraprayag" },
      { day: 11, title: "Return to Haridwar", description: "Drive back to Haridwar / Rishikesh with blessings.", meals: "Breakfast" },
    ],
    inclusions: ["AC vehicle (non-AC in hills)", "Hotels with pure-veg breakfast & dinner", "Group leader & yatra registration", "Oxygen cylinder & first aid", "All tolls & parking"],
    exclusions: ["Pony, palki or helicopter charges", "VIP darshan fees", "Travel to Haridwar", "Personal expenses"],
    groupSizeMax: 24,
    difficulty: "moderate",
    popularity: 82,
    groupSeason: [5, 6, 9, 10],
    seatsPerDeparture: 24,
  },
  {
    slug: "dazzling-dubai",
    title: "Dazzling Dubai with Abu Dhabi",
    destination: "dubai",
    themes: ["family", "luxury", "shopping"],
    route: ["Dubai", "Abu Dhabi"],
    durationDays: 5,
    price: 54999,
    originalPrice: 62999,
    offerDays: 4,
    coverImage: img("1512453979798-5ea266f8880c"),
    gallery: [img("1451337516015-6b6e9a44a8a3"), img("1504150558240-0b4fd8946624"), img("1488646953014-85cb44e25828")],
    summary: "Burj Khalifa, desert safari with BBQ, a Marina dhow cruise and the Grand Mosque.",
    overview:
      "Dubai, fully loaded. Flights, visa and a central 4★ hotel are taken care of, so you can focus on dune bashing at sunset, the 124th-floor views of Burj Khalifa, a dinner cruise in the Marina, and a day in Abu Dhabi at the breathtaking Sheikh Zayed Grand Mosque.",
    highlights: ["Burj Khalifa 'At the Top'", "Desert safari with BBQ dinner", "Marina dhow dinner cruise", "Abu Dhabi city tour"],
    itinerary: [
      { day: 1, title: "Arrive Dubai · Dhow cruise", description: "Arrive and check in. Evening Marina dhow cruise with international buffet.", meals: "Dinner", stay: "4★ hotel, Dubai" },
      { day: 2, title: "City tour · Burj Khalifa", description: "Half-day city tour (Jumeirah, Palm, gold souk) and Burj Khalifa 'At the Top' at sunset.", meals: "Breakfast", stay: "4★ hotel, Dubai" },
      { day: 3, title: "Desert safari", description: "Free morning for shopping. Afternoon dune bashing, camel ride, henna and BBQ dinner with belly dance show.", meals: "Breakfast, Dinner", stay: "4★ hotel, Dubai" },
      { day: 4, title: "Abu Dhabi", description: "Sheikh Zayed Grand Mosque, Qasr Al Watan photo stop and Ferrari World (optional).", meals: "Breakfast", stay: "4★ hotel, Dubai" },
      { day: 5, title: "Departure", description: "Check out and airport transfer.", meals: "Breakfast" },
    ],
    inclusions: [...intlIncl, "Desert safari & dhow cruise", "Burj Khalifa 124th floor tickets"],
    exclusions: ["Tourism Dirham fee (paid at hotel)", "Lunches", "Optional theme parks", "GST & TCS as applicable"],
    groupSizeMax: 12,
    difficulty: "easy",
    featured: true,
    popularity: 97,
  },
  {
    slug: "thailand-bangkok-pattaya-phuket",
    title: "Thailand: Bangkok, Pattaya & Phuket",
    destination: "thailand",
    themes: ["friends", "beach", "honeymoon"],
    route: ["Bangkok", "Pattaya", "Phuket", "Phi Phi"],
    durationDays: 7,
    price: 48999,
    originalPrice: 55999,
    coverImage: img("1552465011-b4e21bf6e79a"),
    gallery: [img("1528181304800-259b08848526"), img("1508009603885-50cf7c579365"), img("1507525428034-b723cf961d3e")],
    summary: "Temples and rooftop bars, Coral Island speedboats and the Phi Phi islands.",
    overview:
      "Three Thailands in one week. Temple-hop and shop in Bangkok, speedboat to Coral Island from Pattaya, then fly south to Phuket for long-tail boats, Maya Bay and the limestone towers of Phi Phi.",
    highlights: ["Phi Phi island tour by speedboat", "Coral Island with lunch", "Bangkok temple & city tour", "Alcazar cabaret show"],
    itinerary: [
      { day: 1, title: "Arrive Bangkok → Pattaya", description: "Transfer to Pattaya. Evening Alcazar cabaret show.", meals: "—", stay: "4★ hotel, Pattaya" },
      { day: 2, title: "Coral Island", description: "Speedboat to Coral Island; parasailing optional. Indian lunch included.", meals: "Breakfast, Lunch", stay: "4★ hotel, Pattaya" },
      { day: 3, title: "Pattaya → Bangkok", description: "Drive to Bangkok; Golden Buddha & Marble temple tour, evening at Pratunam / MBK.", meals: "Breakfast", stay: "4★ hotel, Bangkok" },
      { day: 4, title: "Bangkok → Phuket", description: "Flight to Phuket. Evening on Patong's Bangla Road.", meals: "Breakfast", stay: "4★ hotel, Patong" },
      { day: 5, title: "Phi Phi Islands", description: "Full-day speedboat tour: Maya Bay, Pileh Lagoon, Monkey Beach and snorkelling.", meals: "Breakfast, Lunch", stay: "4★ hotel, Patong" },
      { day: 6, title: "Phuket city tour", description: "Big Buddha, Karon viewpoint, Wat Chalong and Old Phuket Town.", meals: "Breakfast", stay: "4★ hotel, Patong" },
      { day: 7, title: "Departure", description: "Airport transfer.", meals: "Breakfast" },
    ],
    inclusions: [...intlIncl, "Bangkok → Phuket domestic flight", "Coral Island & Phi Phi tours with lunch"],
    exclusions: ["National park fees at Phi Phi", "Lunches & dinners unless mentioned", "GST & TCS as applicable"],
    groupSizeMax: 12,
    difficulty: "easy",
    featured: true,
    popularity: 92,
  },
  {
    slug: "bali-honeymoon-bliss",
    title: "Bali Honeymoon Bliss",
    destination: "bali",
    themes: ["honeymoon", "beach", "luxury"],
    route: ["Ubud", "Kintamani", "Nusa Penida", "Seminyak"],
    durationDays: 6,
    price: 56999,
    originalPrice: 64999,
    offerDays: 7,
    coverImage: img("1537996194471-e657df975ab4"),
    gallery: [img("1518548419970-58e3b4079ab2"), img("1507525428034-b723cf961d3e"), img("1514282401047-d79a71a590e8")],
    summary: "Private pool villa in Ubud, a floating breakfast and candle-lit beach dinner.",
    overview:
      "Designed for two. Wake up in a private pool villa above the jungle, float your breakfast, swing over rice terraces, chase the sunrise from Mount Batur and spend a day on the dramatic cliffs of Nusa Penida before a candle-lit dinner on the sand in Seminyak.",
    highlights: ["Private pool villa in Ubud", "Floating breakfast & flower bath", "Nusa Penida day tour", "Candle-light beach dinner"],
    itinerary: [
      { day: 1, title: "Arrive Bali → Ubud", description: "Welcome with flower garlands and check in to your private pool villa.", meals: "—", stay: "Private pool villa, Ubud" },
      { day: 2, title: "Ubud & Kintamani", description: "Tegallalang rice terraces, jungle swing, coffee plantation and Kintamani volcano views.", meals: "Breakfast, Lunch", stay: "Private pool villa, Ubud" },
      { day: 3, title: "Floating breakfast · Spa", description: "Floating breakfast and a couple's Balinese massage. Evening Kecak fire dance at Uluwatu.", meals: "Breakfast", stay: "Resort in Seminyak" },
      { day: 4, title: "Nusa Penida", description: "Fast boat to Nusa Penida: Kelingking Beach, Broken Beach and Angel's Billabong.", meals: "Breakfast, Lunch", stay: "Resort in Seminyak" },
      { day: 5, title: "Leisure · Beach dinner", description: "Free day for beach clubs, then a candle-light dinner on the beach.", meals: "Breakfast, Dinner", stay: "Resort in Seminyak" },
      { day: 6, title: "Departure", description: "Airport transfer.", meals: "Breakfast" },
    ],
    inclusions: [...intlIncl, "Private pool villa (2 nights)", "Floating breakfast, couple spa & candle-light dinner", "Nusa Penida tour with lunch"],
    exclusions: ["Visa on arrival fee", "Bali tourism levy", "GST & TCS as applicable"],
    groupSizeMax: 2,
    difficulty: "easy",
    featured: true,
    popularity: 94,
  },
  {
    slug: "maldives-overwater-retreat",
    title: "Maldives Overwater Villa Retreat",
    destination: "maldives",
    themes: ["luxury", "honeymoon", "beach"],
    route: ["Malé", "Resort island"],
    durationDays: 4,
    price: 89999,
    originalPrice: 1_04_999,
    coverImage: img("1514282401047-d79a71a590e8"),
    gallery: [img("1507525428034-b723cf961d3e"), img("1544551763-46a013bb70d5"), img("1506929562872-bb421503ef21")],
    summary: "Three nights in a water villa with all meals, speedboat transfers and a sandbank picnic.",
    overview:
      "Your own deck above a turquoise lagoon. Arrive by speedboat to a 5★ island resort, settle into an overwater villa with all meals included, snorkel with reef sharks and turtles, and enjoy a private sandbank picnic you will talk about for years.",
    highlights: ["Overwater villa stay", "All meals included", "Snorkelling excursion", "Sandbank picnic"],
    itinerary: [
      { day: 1, title: "Arrive Malé → Resort", description: "Speedboat transfer to the resort and check in to your water villa.", meals: "Lunch, Dinner", stay: "Water villa" },
      { day: 2, title: "Reef & relax", description: "Guided snorkelling trip with turtles and reef fish; spa time in the afternoon.", meals: "All meals", stay: "Water villa" },
      { day: 3, title: "Sandbank picnic", description: "Private sandbank picnic and sunset dolphin cruise.", meals: "All meals", stay: "Water villa" },
      { day: 4, title: "Departure", description: "Speedboat transfer back to Malé airport.", meals: "Breakfast" },
    ],
    inclusions: ["3 nights water villa", "All meals (full board)", "Return speedboat transfers", "Snorkelling trip & sandbank picnic", "Green tax"],
    exclusions: ["Airfare to Malé", "Seaplane upgrade", "Alcoholic beverages", "GST & TCS as applicable"],
    groupSizeMax: 4,
    difficulty: "easy",
    popularity: 89,
  },
  {
    slug: "singapore-malaysia-family-fiesta",
    title: "Singapore & Malaysia Family Fiesta",
    destination: "singapore-malaysia",
    themes: ["family", "shopping"],
    route: ["Singapore", "Sentosa", "Genting", "Kuala Lumpur"],
    durationDays: 7,
    price: 74999,
    coverImage: img("1525625293386-3f8f99389edd"),
    gallery: [img("1488646953014-85cb44e25828"), img("1540959733332-eab4deabeeaf"), img("1507525428034-b723cf961d3e")],
    summary: "Universal Studios, Sentosa, Night Safari, Genting Highlands and the Petronas Towers.",
    overview:
      "The family favourite. Thrill rides at Universal Studios, cable cars to Sentosa, a Night Safari, the light show at Gardens by the Bay, then a coach across to Malaysia for Genting Highlands and the twin towers of Kuala Lumpur.",
    highlights: ["Universal Studios Singapore", "Night Safari", "Sentosa with cable car", "Genting Highlands & Batu Caves"],
    itinerary: [
      { day: 1, title: "Arrive Singapore", description: "Check in; evening Gardens by the Bay light show.", meals: "Dinner", stay: "4★ hotel, Singapore" },
      { day: 2, title: "City tour & Night Safari", description: "Merlion, Marina Bay, Chinatown, then the world's first Night Safari.", meals: "Breakfast, Dinner", stay: "4★ hotel, Singapore" },
      { day: 3, title: "Universal Studios", description: "Full day at Universal Studios Singapore.", meals: "Breakfast, Dinner", stay: "4★ hotel, Singapore" },
      { day: 4, title: "Sentosa", description: "Cable car, SEA Aquarium and Wings of Time show.", meals: "Breakfast, Dinner", stay: "4★ hotel, Singapore" },
      { day: 5, title: "Singapore → Genting", description: "Coach to Malaysia and Awana SkyWay cable car to Genting Highlands.", meals: "Breakfast, Dinner", stay: "Hotel in Genting" },
      { day: 6, title: "Kuala Lumpur", description: "Batu Caves, Petronas Towers photo stop and KL city tour.", meals: "Breakfast, Dinner", stay: "4★ hotel, Kuala Lumpur" },
      { day: 7, title: "Departure", description: "Airport transfer from Kuala Lumpur.", meals: "Breakfast" },
    ],
    inclusions: [...intlIncl, "Universal Studios, Night Safari & Sentosa tickets", "Indian dinners daily"],
    exclusions: ["Lunches", "Optional tours", "GST & TCS as applicable"],
    groupSizeMax: 12,
    difficulty: "easy",
    popularity: 85,
  },
  {
    slug: "europe-grand-tour",
    title: "Europe Grand Tour: Paris, Swiss Alps & Italy",
    destination: "europe",
    themes: ["group", "culture", "luxury"],
    route: ["Paris", "Lucerne", "Interlaken", "Venice", "Florence", "Rome"],
    durationDays: 12,
    price: 2_49_999,
    originalPrice: 2_79_999,
    offerDays: 10,
    coverImage: img("1530122037265-a5f1f91d3b99"),
    gallery: [img("1502602898657-3e91760cbb34"), img("1523906834658-6e24ef2386f9"), img("1476514525535-07fb3b4ae5f1")],
    summary: "A tour-manager-led group journey with Jungfraujoch, a Seine cruise and Venice gondolas.",
    overview:
      "Europe's greatest hits with an Indian tour manager, Indian dinners and a small-group feel. From the Eiffel Tower and the Seine to the snows of Jungfraujoch, the canals of Venice, Renaissance Florence and the Colosseum in Rome — every visa, ticket and transfer handled.",
    highlights: ["Indian tour manager throughout", "Jungfraujoch – Top of Europe", "Seine cruise & Eiffel Tower level 2", "Venice gondola ride", "Vatican Museums & Colosseum"],
    itinerary: [
      { day: 1, title: "Arrive Paris", description: "Welcome dinner and an evening illumination tour of Paris.", meals: "Dinner", stay: "4★ hotel, Paris" },
      { day: 2, title: "Paris", description: "Eiffel Tower level 2, Seine cruise and a guided city tour.", meals: "Breakfast, Dinner", stay: "4★ hotel, Paris" },
      { day: 3, title: "Disneyland or Louvre", description: "Choose Disneyland Paris or the Louvre & Montmartre.", meals: "Breakfast, Dinner", stay: "4★ hotel, Paris" },
      { day: 4, title: "Paris → Lucerne", description: "TGV / coach to Switzerland. Chapel Bridge and Lion Monument.", meals: "Breakfast, Dinner", stay: "Hotel in Central Switzerland" },
      { day: 5, title: "Mt Titlis", description: "Rotair revolving cable car to the glaciers of Mt Titlis.", meals: "Breakfast, Dinner", stay: "Hotel in Central Switzerland" },
      { day: 6, title: "Jungfraujoch", description: "Cogwheel train to the Top of Europe; afternoon in Interlaken.", meals: "Breakfast, Dinner", stay: "Hotel in Central Switzerland" },
      { day: 7, title: "Switzerland → Venice", description: "Scenic drive through the Alps to the Venice region.", meals: "Breakfast, Dinner", stay: "Hotel in Venice region" },
      { day: 8, title: "Venice", description: "Private boat to St Mark's Square and a gondola ride.", meals: "Breakfast, Dinner", stay: "Hotel in Venice region" },
      { day: 9, title: "Pisa & Florence", description: "Leaning Tower of Pisa and Florence's Duomo & Piazzale Michelangelo.", meals: "Breakfast, Dinner", stay: "Hotel in Florence" },
      { day: 10, title: "Rome", description: "Colosseum (outside), Trevi Fountain and Roman Forum.", meals: "Breakfast, Dinner", stay: "Hotel in Rome" },
      { day: 11, title: "Vatican City", description: "Vatican Museums, Sistine Chapel and St Peter's Basilica. Farewell dinner.", meals: "Breakfast, Dinner", stay: "Hotel in Rome" },
      { day: 12, title: "Departure", description: "Transfer to Rome airport for your flight home.", meals: "Breakfast" },
    ],
    inclusions: ["Return economy airfare", "Schengen visa fees & travel insurance", "4★ hotels with breakfast & Indian dinners", "Indian tour manager", "All sightseeing & entry tickets listed", "Coach, TGV & boat transfers"],
    exclusions: ["City taxes paid at hotels", "Lunches", "Tips to driver & guides", "GST & TCS as applicable"],
    groupSizeMax: 30,
    difficulty: "moderate",
    featured: true,
    popularity: 91,
    groupSeason: [4, 5, 6, 7, 8, 9, 10],
    seatsPerDeparture: 30,
  },
  {
    slug: "vietnam-discovery",
    title: "Vietnam Discovery: Hanoi, Ha Long & Hoi An",
    destination: "vietnam",
    themes: ["culture", "group", "nature"],
    route: ["Hanoi", "Ha Long Bay", "Da Nang", "Hoi An", "Ho Chi Minh City"],
    durationDays: 8,
    price: 69999,
    coverImage: img("1528127269322-539801943592"),
    gallery: [img("1583417319070-4a69db38a482"), img("1559592413-7cec4d0cae2b"), img("1507525428034-b723cf961d3e")],
    summary: "An overnight Ha Long cruise, Golden Bridge at Ba Na Hills and lantern-lit Hoi An.",
    overview:
      "Vietnam from north to south with a small group. Street-food crawl in Hanoi's Old Quarter, sleep aboard a cruise among Ha Long Bay's limestone karsts, walk the giant hands of the Golden Bridge, float lanterns in Hoi An and crawl through the Cu Chi tunnels near Saigon.",
    highlights: ["Overnight Ha Long Bay cruise", "Golden Bridge at Ba Na Hills", "Hoi An lantern evening", "Cu Chi tunnels"],
    itinerary: [
      { day: 1, title: "Arrive Hanoi", description: "Old Quarter walk, water puppet show and street-food tasting.", meals: "Dinner", stay: "4★ hotel, Hanoi" },
      { day: 2, title: "Hanoi → Ha Long Bay cruise", description: "Board your cruise; kayaking and a cave visit among the karsts.", meals: "All meals", stay: "Overnight cruise" },
      { day: 3, title: "Ha Long → Hanoi → Da Nang", description: "Sunrise tai-chi on deck, then fly to Da Nang.", meals: "Breakfast", stay: "Beach hotel, Da Nang" },
      { day: 4, title: "Ba Na Hills", description: "Cable car to Ba Na Hills and the iconic Golden Bridge.", meals: "Breakfast, Lunch", stay: "Beach hotel, Da Nang" },
      { day: 5, title: "Hoi An", description: "Hoi An ancient town, tailor shops and a lantern boat at dusk.", meals: "Breakfast", stay: "Hotel in Hoi An" },
      { day: 6, title: "Fly to Ho Chi Minh City", description: "Saigon city tour: Notre-Dame, Post Office and Ben Thanh market.", meals: "Breakfast", stay: "4★ hotel, HCMC" },
      { day: 7, title: "Cu Chi tunnels & Mekong", description: "Cu Chi tunnels in the morning, Mekong Delta boat ride after lunch.", meals: "Breakfast, Lunch", stay: "4★ hotel, HCMC" },
      { day: 8, title: "Departure", description: "Airport transfer.", meals: "Breakfast" },
    ],
    inclusions: [...intlIncl, "Overnight Ha Long cruise with meals", "2 internal flights"],
    exclusions: ["Dinners unless mentioned", "Tips", "GST & TCS as applicable"],
    groupSizeMax: 20,
    difficulty: "moderate",
    popularity: 79,
    groupSeason: [10, 11, 12, 1, 2, 3, 4],
    seatsPerDeparture: 20,
  },
  {
    slug: "japan-cherry-blossom-trail",
    title: "Japan: Cherry Blossoms to Neon Nights",
    destination: "japan",
    themes: ["culture", "group", "luxury"],
    route: ["Tokyo", "Mt Fuji", "Hakone", "Kyoto", "Nara", "Osaka"],
    durationDays: 9,
    price: 1_89_999,
    coverImage: img("1493976040374-85c8e12f0c0e"),
    gallery: [img("1540959733332-eab4deabeeaf"), img("1503899036084-c55cdd92da26"), img("1476514525535-07fb3b4ae5f1")],
    summary: "Tokyo, Mt Fuji, a bullet train to Kyoto and Osaka street food — timed for blossom & autumn colours.",
    overview:
      "A beautifully choreographed group journey through Japan in its most photogenic seasons. Shibuya and Senso-ji in Tokyo, a lake cruise beneath Mt Fuji, a night in a traditional ryokan with onsen, the Shinkansen to Kyoto's temples and bamboo groves, Nara's friendly deer and the neon food streets of Osaka.",
    highlights: ["Shinkansen bullet train", "Ryokan night with onsen", "Mt Fuji 5th station & Lake Ashi cruise", "Fushimi Inari & Arashiyama bamboo grove"],
    itinerary: [
      { day: 1, title: "Arrive Tokyo", description: "Meet your tour manager and transfer to your hotel in Shinjuku.", meals: "Dinner", stay: "Hotel in Tokyo" },
      { day: 2, title: "Tokyo highlights", description: "Senso-ji, Meiji Shrine, Shibuya crossing and Tokyo Skytree.", meals: "Breakfast, Dinner", stay: "Hotel in Tokyo" },
      { day: 3, title: "Tokyo free day", description: "Optional Disneyland / teamLab, or explore Akihabara and Harajuku.", meals: "Breakfast", stay: "Hotel in Tokyo" },
      { day: 4, title: "Mt Fuji & Hakone", description: "Fuji 5th station, Lake Ashi cruise and Hakone ropeway. Ryokan stay with onsen.", meals: "Breakfast, Dinner", stay: "Ryokan in Hakone" },
      { day: 5, title: "Bullet train to Kyoto", description: "Shinkansen to Kyoto; Kinkaku-ji golden pavilion and Gion stroll.", meals: "Breakfast, Dinner", stay: "Hotel in Kyoto" },
      { day: 6, title: "Kyoto", description: "Fushimi Inari's thousand gates, Kiyomizu-dera and Arashiyama bamboo grove.", meals: "Breakfast, Dinner", stay: "Hotel in Kyoto" },
      { day: 7, title: "Nara → Osaka", description: "Nara deer park and Todai-ji, then Osaka Castle and Dotonbori by night.", meals: "Breakfast", stay: "Hotel in Osaka" },
      { day: 8, title: "Osaka / Universal Studios", description: "Free day or optional Universal Studios Japan.", meals: "Breakfast, Dinner", stay: "Hotel in Osaka" },
      { day: 9, title: "Departure", description: "Transfer to Kansai airport.", meals: "Breakfast" },
    ],
    inclusions: ["Return economy airfare", "Japan visa assistance & travel insurance", "Hotels + 1 ryokan night", "Shinkansen tickets", "Indian tour manager", "Sightseeing as per itinerary"],
    exclusions: ["Lunches", "Optional theme parks", "GST & TCS as applicable"],
    groupSizeMax: 24,
    difficulty: "moderate",
    featured: true,
    popularity: 87,
    groupSeason: [3, 4, 11],
    seatsPerDeparture: 24,
  },
  {
    slug: "bhutan-land-of-happiness",
    title: "Bhutan: Land of Happiness",
    destination: "bhutan",
    themes: ["culture", "nature", "group"],
    route: ["Phuentsholing", "Thimphu", "Punakha", "Paro"],
    durationDays: 7,
    price: 45999,
    coverImage: img("1553856622-d1b352e9a211"),
    gallery: [img("1464822759023-fed622ff2c3b"), img("1469474968028-56623f02e42e"), img("1454496522488-7a8e488e8606")],
    summary: "Thimphu, Punakha Dzong, Dochula Pass and the hike to Tiger's Nest.",
    overview:
      "Step into a kingdom like no other. Cross Dochula Pass and its 108 chortens, marvel at Punakha Dzong at the meeting of two rivers, spin prayer wheels in Thimphu and finish with the unforgettable hike to Paro Taktsang — the Tiger's Nest monastery clinging to a cliff.",
    highlights: ["Tiger's Nest hike", "Punakha Dzong", "Dochula Pass 108 chortens", "Traditional farmhouse dinner"],
    itinerary: [
      { day: 1, title: "Bagdogra → Phuentsholing", description: "Pick-up and drive to the Bhutan border town.", meals: "Dinner", stay: "Hotel in Phuentsholing" },
      { day: 2, title: "Phuentsholing → Thimphu", description: "Permit formalities and a scenic mountain drive to the capital.", meals: "Breakfast, Dinner", stay: "Hotel in Thimphu" },
      { day: 3, title: "Thimphu", description: "Buddha Dordenma, Memorial Chorten, Takin preserve and the weekend market.", meals: "Breakfast, Dinner", stay: "Hotel in Thimphu" },
      { day: 4, title: "Thimphu → Punakha", description: "Dochula Pass, then Punakha Dzong and the suspension bridge.", meals: "Breakfast, Dinner", stay: "Hotel in Punakha" },
      { day: 5, title: "Punakha → Paro", description: "Drive to Paro; Rinpung Dzong and National Museum.", meals: "Breakfast, Dinner", stay: "Hotel in Paro" },
      { day: 6, title: "Tiger's Nest", description: "Hike to Paro Taktsang (approx. 5 hrs return). Farmhouse dinner with hot stone bath option.", meals: "Breakfast, Dinner", stay: "Hotel in Paro" },
      { day: 7, title: "Departure", description: "Drive back to Phuentsholing / Bagdogra.", meals: "Breakfast" },
    ],
    inclusions: [...stdIncl, "Bhutan entry permits", "Licensed Bhutanese guide"],
    exclusions: [...stdExcl, "Sustainable Development Fee (SDF) where applicable", "Pony for Tiger's Nest"],
    groupSizeMax: 16,
    difficulty: "moderate",
    popularity: 76,
    groupSeason: [3, 4, 5, 9, 10, 11],
    seatsPerDeparture: 16,
  },
];

/**
 * Sample reviews so the site looks complete in development.
 * ⚠️ Replace these with genuine customer reviews before going live —
 * run `npm run db:reset -- --no-demo-reviews` to start with an empty review list.
 */
export const seedReviews: {
  pkg: string;
  name: string;
  location: string;
  rating: number;
  title: string;
  comment: string;
  tripType: string;
  daysAgo: number;
  featured?: boolean;
}[] = [
  { pkg: "kashmir-paradise-on-earth", name: "Ananya & Rohit", location: "Pune", rating: 5, title: "Our honeymoon was pure magic", comment: "The houseboat night, the shikara at sunset with kahwa, Gulmarg in the snow — every single day felt planned with love. Our driver Bashir bhai became family. Thank you Explore Bound!", tripType: "Honeymoon", daysAgo: 12, featured: true },
  { pkg: "leh-ladakh-bike-expedition", name: "Karan Mehta", location: "Bengaluru", rating: 5, title: "Ride of a lifetime", comment: "Road captain was a legend, mechanic fixed a puncture at Khardung La in 10 minutes and the backup vehicle carried our bags. Pangong at sunrise made me tear up. Already booked Spiti for next year.", tripType: "Group tour", daysAgo: 40, featured: true },
  { pkg: "dazzling-dubai", name: "The Sharma Family", location: "Delhi", rating: 5, title: "Kids still talk about the desert safari", comment: "Visa came in 3 days, hotel was central and every pick-up was on time. Burj Khalifa at sunset was the highlight. Great value for a family of five.", tripType: "Family", daysAgo: 25, featured: true },
  { pkg: "kerala-gods-own-country", name: "Meera Iyer", location: "Chennai", rating: 5, title: "The houseboat food alone is worth it", comment: "Munnar mist, spice walk in Thekkady and that private houseboat… the chef made the best karimeen pollichathu. Very well-paced itinerary for my parents.", tripType: "Family", daysAgo: 60, featured: true },
  { pkg: "bali-honeymoon-bliss", name: "Sneha & Arjun", location: "Hyderabad", rating: 5, title: "Pool villa + floating breakfast = heaven", comment: "Everything from the flower bath to the candle-light dinner was perfect. Nusa Penida was breathtaking. Explore Bound checked on us daily on WhatsApp without being intrusive.", tripType: "Honeymoon", daysAgo: 18, featured: true },
  { pkg: "europe-grand-tour", name: "Rajesh Kulkarni", location: "Mumbai", rating: 5, title: "Seamless Europe for my parents' 35th anniversary", comment: "Tour manager Nikhil was outstanding. Indian dinners every night made my parents very happy. Jungfraujoch and Venice were dreamlike. Visa documentation help was superb.", tripType: "Group tour", daysAgo: 90, featured: true },
  { pkg: "thailand-bangkok-pattaya-phuket", name: "Vikram Singh", location: "Jaipur", rating: 4, title: "Fun trip with the boys", comment: "Phi Phi island tour was incredible and Coral Island was a blast. Hotel in Pattaya could be closer to the beach, but overall great value and super responsive team.", tripType: "Friends", daysAgo: 33, featured: true },
  { pkg: "andaman-island-hopping", name: "Priya Nair", location: "Kochi", rating: 5, title: "First scuba dive, never forgetting it", comment: "I can't swim and still did a scuba dive at Havelock thanks to the amazing instructors. Radhanagar sunset was unreal. Ferries and hotels all pre-booked — zero stress.", tripType: "Solo", daysAgo: 52, featured: true },
  { pkg: "royal-rajasthan", name: "Aditya Rao", location: "Nagpur", rating: 5, title: "Felt like royalty", comment: "Heritage hotels were stunning and the desert camp night with folk music was the best part. Driver knew all the best photo spots.", tripType: "Family", daysAgo: 75 },
  { pkg: "char-dham-yatra", name: "Sushila Deshpande", location: "Nashik", rating: 5, title: "Blessed and well cared for", comment: "At 62 I was nervous about Kedarnath but the team arranged a pony and checked on me throughout. Clean hotels, pure veg food and a very kind group leader. Jai Badri Vishal!", tripType: "Pilgrimage", daysAgo: 120, featured: true },
  { pkg: "maldives-overwater-retreat", name: "Neha Kapoor", location: "Gurugram", rating: 5, title: "Worth every rupee", comment: "Water villa was gorgeous and the sandbank picnic was the most romantic experience of our lives. Speedboat transfers were smooth.", tripType: "Anniversary", daysAgo: 30 },
  { pkg: "shimla-manali-delight", name: "Rahul Verma", location: "Lucknow", rating: 4, title: "Great first trip to the hills", comment: "Solang valley snow was a hit with the kids. Traffic near Manali was heavy (not their fault). Hotels were clean and food was good.", tripType: "Family", daysAgo: 15 },
  { pkg: "goa-beach-escape", name: "Ishita Bose", location: "Kolkata", rating: 4, title: "Perfect girls' getaway", comment: "Resort was lovely, sunset cruise was fun and the water sports combo was great value. Would have liked one more free day!", tripType: "Friends", daysAgo: 8 },
  { pkg: "singapore-malaysia-family-fiesta", name: "Farhan Qureshi", location: "Bhopal", rating: 5, title: "Universal Studios made our kids' year", comment: "Everything was super organised — tickets, Indian dinners, the coach to Genting. Night Safari was a surprise favourite.", tripType: "Family", daysAgo: 66 },
  { pkg: "sikkim-darjeeling-trail", name: "Tanvi Joshi", location: "Ahmedabad", rating: 5, title: "Kanchenjunga at sunrise!", comment: "Yumthang valley was covered in flowers and Zero Point had fresh snow. Tiger Hill sunrise was magical. Lodges in Lachung were basic but warm and cosy.", tripType: "Family", daysAgo: 95 },
  { pkg: "japan-cherry-blossom-trail", name: "Deepak & Kavya", location: "Bengaluru", rating: 5, title: "Japan exceeded every expectation", comment: "Timed perfectly for sakura. The ryokan night with onsen, the bullet train and Fushimi Inari at dawn — just wow. Tour manager handled everything.", tripType: "Group tour", daysAgo: 160 },
  { pkg: "vietnam-discovery", name: "Siddharth Jain", location: "Indore", rating: 4, title: "Ha Long cruise was the highlight", comment: "Loved Hoi An and the Golden Bridge. Long day of travel on day 3 but worth it. Vegetarian food arrangements were well handled.", tripType: "Group tour", daysAgo: 140 },
  { pkg: "bhutan-land-of-happiness", name: "Pooja Reddy", location: "Vizag", rating: 5, title: "Peace like nowhere else", comment: "Tiger's Nest hike was tough but so rewarding. Our guide Karma was incredibly knowledgeable. Bhutan is a must!", tripType: "Friends", daysAgo: 200 },
  { pkg: "golden-triangle-tour", name: "Michael & Sarah Thompson", location: "London, UK", rating: 5, title: "Perfect introduction to India", comment: "Our guides were brilliant storytellers and the Taj at sunrise was everything we hoped for. Felt safe and looked after the whole time.", tripType: "Couple", daysAgo: 48 },
  { pkg: "spiti-valley-expedition", name: "Aman Gill", location: "Chandigarh", rating: 5, title: "Raw, remote and unforgettable", comment: "Chandratal under the stars and posting a letter from Hikkim — bucket list ticked. Trip captain was very safety-conscious.", tripType: "Group tour", daysAgo: 110 },
  { pkg: "dazzling-dubai", name: "Ritu Agarwal", location: "Surat", rating: 4, title: "Smooth and well organised", comment: "Loved the dhow cruise and desert safari. Abu Dhabi day was long but the Grand Mosque is a must-see.", tripType: "Family", daysAgo: 70 },
  { pkg: "kashmir-paradise-on-earth", name: "Harsh Vardhan", location: "Indore", rating: 5, title: "Took my parents, they loved it", comment: "Pahalgam valleys were heavenly and the hotels were excellent. The team even arranged a wheelchair at the Mughal gardens for my father.", tripType: "Family", daysAgo: 85 },
  { pkg: "leh-ladakh-bike-expedition", name: "Nikita Rawat", location: "Dehradun", rating: 5, title: "Rode my own bike as the only girl in the group", comment: "Felt completely safe and supported. The group became friends for life. Turtuk's apricot orchards were a hidden gem.", tripType: "Group tour", daysAgo: 300 },
  { pkg: "thailand-bangkok-pattaya-phuket", name: "Ayesha Khan", location: "Mumbai", rating: 3, title: "Good trip, a few hiccups", comment: "Tours were fun but our Bangkok pick-up was 40 minutes late. The team apologised and upgraded our Phuket room though, which we appreciated.", tripType: "Couple", daysAgo: 130 },
];
